version: '2'
services:
  web:
    build: .
    command: npm run dev
    restart: unless-stopped
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true